"use client";

import { AppLayout } from "@/components/layout/app-layout";
import { Input } from "@/components/ui/input";
import { useEffect, useMemo, useRef, useState } from "react";
import type { NoteListItem } from "@/lib/supabase/types";

type GraphNode = {
  id: string;
  label: string;
  summary: string | null;
  tags: string[];
  concepts: string[];
  source: string | null;
  sourceUrl: string | null;
  captureItemId: string | null;
  createdAt: string;
  updatedAt: string;
  degree: number;
};

type GraphEdge = {
  id: string;
  source: string;
  target: string;
  type: string;
  confidence: number | null;
  evidence: Record<string, unknown> | null;
  isAutoGenerated: boolean | null;
  createdAt: string;
};

type GraphResponse = {
  nodes: GraphNode[];
  edges: GraphEdge[];
  meta: {
    nodeCount: number;
    edgeCount: number;
    truncated: boolean;
    limit: number;
    focusNoteId?: string | null;
  };
};

type NoteDetailResponse = {
  note: NoteListItem & { content?: string | null };
  relations: Array<{
    id: string;
    source_note_id: string;
    target_note_id: string;
    relation_type: string;
  }>;
};

const RELATION_COLORS: Record<string, string> = {
  related: "#6B7280",
  extends: "#2563EB",
  contradicts: "#DC2626",
  derives_from: "#16A34A",
};

function relationColor(type: string) {
  return RELATION_COLORS[type] || "#6B7280";
}

function formatDate(iso: string) {
  const d = new Date(iso);
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${mm}-${dd}`;
}

export default function KbPage() {
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [graphData, setGraphData] = useState<GraphResponse | null>(null);
  const [activeNoteId, setActiveNoteId] = useState<string | null>(null);
  const [activeNote, setActiveNote] = useState<(NoteListItem & { content?: string | null }) | null>(null);
  const [relatedIds, setRelatedIds] = useState<string[]>([]);
  const [relatedRelations, setRelatedRelations] = useState<Array<{ id: string; otherId: string; type: string }>>([]);
  const [selectedRelationTypes, setSelectedRelationTypes] = useState<string[]>([]);
  const [onlyActiveNeighborhood, setOnlyActiveNeighborhood] = useState(false);
  const [onlyHighConfidence, setOnlyHighConfidence] = useState(false);
  const [reloadKey, setReloadKey] = useState(0);
  const [newRelationTargetId, setNewRelationTargetId] = useState("");
  const [newRelationType, setNewRelationType] = useState("related");
  const [viewReady, setViewReady] = useState(false);
  const [toast, setToast] = useState<{ type: "success" | "error"; message: string } | null>(null);
  const [editingRelationTypes, setEditingRelationTypes] = useState<Record<string, string>>({});

  const graphWrapRef = useRef<HTMLDivElement | null>(null);
  const graphRef = useRef<any>(null);
  const selectedNodeRef = useRef<string | null>(null);
  const persistBoundRef = useRef(false);
  const shouldZoomOnSelectRef = useRef(false);
  const captureItemId = useMemo(() => {
    if (typeof window === "undefined") return null;
    return new URLSearchParams(window.location.search).get("captureItemId");
  }, []);
  const storageKey = "innex_kb_graph_view_v1";
  const graphCacheKey = "innex_kb_graph_cache_v1";

  useEffect(() => {
    if (typeof window === "undefined") return;
    const params = new URLSearchParams(window.location.search);
    const rel = params.get("rel");
    const node = params.get("node");
    const only = params.get("onlyActive");
    const hc = params.get("hc");
    if (rel) {
      const values = rel.split(",").map((x) => x.trim()).filter(Boolean);
      if (values.length) setSelectedRelationTypes(values);
    }
    if (node) setActiveNoteId(node);
    if (only === "1") setOnlyActiveNeighborhood(true);
    if (hc === "1") setOnlyHighConfidence(true);
    try {
      const cached = window.localStorage.getItem(graphCacheKey);
      if (cached) {
        const parsed = JSON.parse(cached) as GraphResponse;
        if (parsed?.nodes && parsed?.edges) {
          setGraphData(parsed);
          setLoading(false);
        }
      }
    } catch {
      // ignore cache errors
    }
    setViewReady(true);
  }, []);

  const relationTypes = useMemo(() => {
    const set = new Set<string>();
    for (const e of graphData?.edges || []) set.add(e.type || "related");
    return Array.from(set);
  }, [graphData]);

  useEffect(() => {
    if (!viewReady || relationTypes.length === 0) return;
    if (selectedRelationTypes.length === 0) {
      setSelectedRelationTypes(relationTypes);
      return;
    }
    const exists = new Set(relationTypes);
    const next = selectedRelationTypes.filter((x) => exists.has(x));
    if (next.length !== selectedRelationTypes.length) {
      setSelectedRelationTypes(next.length ? next : relationTypes);
    }
  }, [relationTypes, selectedRelationTypes, viewReady]);

  const filteredGraph = useMemo(() => {
    const base = graphData || {
      nodes: [],
      edges: [],
      meta: { nodeCount: 0, edgeCount: 0, truncated: false, limit: 300 },
    };
    if (!selectedRelationTypes.length) return base;

    const allow = new Set(selectedRelationTypes);
    let edges = base.edges.filter((e) => allow.has(e.type || "related"));
    if (onlyHighConfidence) {
      edges = edges.filter((e) => (typeof e.confidence === "number" ? e.confidence >= 0.75 : false));
    }
    const nodes = base.nodes;
    let finalEdges = edges;

    return {
      ...base,
      nodes,
      edges: finalEdges,
      meta: {
        ...base.meta,
        nodeCount: nodes.length,
        edgeCount: finalEdges.length,
      },
    };
  }, [graphData, selectedRelationTypes, onlyHighConfidence]);

  useEffect(() => {
    let cancelled = false;
    const run = async () => {
      setLoading(true);
      setError(null);
      try {
        const params = new URLSearchParams();
        if (search.trim()) params.set("search", search.trim());
        params.set("limit", "300");
        if (captureItemId) params.set("focusNoteId", captureItemId);
        const res = await fetch(`/api/graph?${params.toString()}`);
        if (!res.ok) throw new Error("图谱加载失败");
        const data = (await res.json()) as GraphResponse;
        if (cancelled) return;
        setGraphData(data);

        try {
          window.localStorage.setItem(graphCacheKey, JSON.stringify(data));
        } catch {
          // ignore
        }

        if (!activeNoteId && data.nodes.length > 0) {
          const byCapture = captureItemId ? data.nodes.find((n) => n.captureItemId === captureItemId) : null;
          setActiveNoteId(byCapture?.id || data.nodes[0].id);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "图谱加载失败");
          setGraphData({ nodes: [], edges: [], meta: { nodeCount: 0, edgeCount: 0, truncated: false, limit: 300 } });
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    run();
    return () => {
      cancelled = true;
    };
  }, [search, captureItemId, reloadKey]);

  useEffect(() => {
    if (!viewReady || typeof window === "undefined") return;
    const params = new URLSearchParams(window.location.search);
    if (selectedRelationTypes.length && relationTypes.length) params.set("rel", selectedRelationTypes.join(","));
    else params.delete("rel");
    if (activeNoteId) params.set("node", activeNoteId);
    else params.delete("node");
    if (onlyActiveNeighborhood) params.set("onlyActive", "1");
    else params.delete("onlyActive");
    if (onlyHighConfidence) params.set("hc", "1");
    else params.delete("hc");
    const q = params.toString();
    window.history.replaceState({}, "", `${window.location.pathname}${q ? `?${q}` : ""}`);
  }, [selectedRelationTypes, activeNoteId, onlyActiveNeighborhood, onlyHighConfidence, relationTypes.length, viewReady]);

  useEffect(() => {
    if (!graphWrapRef.current || !graphData) return;
    let disposed = false;
    (async () => {
      const mod = await import("@antv/g6");
      if (disposed || !graphWrapRef.current) return;
      const { Graph } = mod;
      if (!graphRef.current) {
        graphRef.current = new Graph({
          container: graphWrapRef.current,
          autoFit: "view",
          data: { nodes: [], edges: [] },
          animation: false,
          node: {
            style: {
              labelText: function (this: any, data: any) {
                const text = String(data.label || "");
                return text.length > 10 ? `${text.slice(0, 10)}...` : text;
              },
              labelPlacement: "bottom",
              labelMaxWidth: 100,
              labelFontSize: 9,
              labelFill: "rgba(78,74,67,0.85)",
              size: function (this: any, data: any) {
                return 16 + Math.min((data.degree || 0) * 2, 18);
              },
              fill: "#F15A24",
              fillOpacity: 0.2,
              stroke: "#F15A24",
              lineWidth: 1.5,
            },
          },
          edge: {
            style: {
              stroke: function (this: any, data: any) {
                return relationColor(data.type || "related");
              },
              strokeOpacity: function (this: any, data: any) {
                if (typeof data.confidence !== "number") return 0.35;
                return Math.max(0.25, Math.min(0.9, data.confidence));
              },
              lineWidth: 1,
              endArrow: false,
            },
          },
          layout: {
            type: "force",
            preventOverlap: true,
            linkDistance: 92,
            nodeStrength: -120,
            edgeStrength: 0.22,
            gravity: 0.2,
            collideStrength: 0.9,
            nodeSize: 24,
          },
          behaviors: ["drag-canvas", "zoom-canvas", "drag-element", "hover-activate"],
        });

        graphRef.current.on("node:click", (evt: { target?: { id?: string } }) => {
          const id = evt?.target?.id;
          if (id) {
            shouldZoomOnSelectRef.current = true;
            setActiveNoteId(id);
          }
        });
      }

      const graph = graphRef.current;
      graph.setData({
        nodes: filteredGraph.nodes.map((n) => ({ ...n, id: n.id })),
        edges: filteredGraph.edges.map((e) => ({ ...e, source: e.source, target: e.target, id: e.id })),
      });
      if (typeof graph.draw === "function") {
        graph.draw();
      } else {
        graph.render();
      }

      try {
        const raw = window.localStorage.getItem(storageKey);
        if (raw) {
          const saved = JSON.parse(raw) as { zoom?: number; x?: number; y?: number };
          const graph = graphRef.current;
          if (graph) {
            requestAnimationFrame(() => {
              try {
                if (typeof saved.zoom === "number" && saved.zoom > 0 && typeof graph.zoomTo === "function") {
                  graph.zoomTo(saved.zoom);
                }
                if (
                  typeof saved.x === "number" &&
                  typeof saved.y === "number" &&
                  typeof graph.translateTo === "function"
                ) {
                  graph.translateTo([saved.x, saved.y]);
                }
              } catch {
                // ignore view restore failures when graph transform not ready
              }
            });
          }
        }
      } catch {
        // ignore
      }

      if (!persistBoundRef.current) {
        const persistView = () => {
          try {
            const zoom = graphRef.current.getZoom();
            const pos = graphRef.current.getPosition();
            window.localStorage.setItem(storageKey, JSON.stringify({ zoom, x: pos?.[0], y: pos?.[1] }));
          } catch {
            // ignore
          }
        };
        graphRef.current.on("aftertransform", persistView);
        persistBoundRef.current = true;
      }
    })();

    return () => {
      disposed = true;
    };
  }, [filteredGraph, graphData]);

  useEffect(() => {
    if (!graphRef.current || !activeNoteId) return;
    const graph = graphRef.current;
    const prev = selectedNodeRef.current;
    if (prev && prev !== activeNoteId) {
      graph.setElementState(prev, "inactive", false);
      graph.setElementState(prev, "selected", false);
    }

    const neighborNodeIds = new Set<string>();
    const neighborEdgeIds = new Set<string>();
    for (const edge of filteredGraph.edges || []) {
      if (edge.source === activeNoteId) {
        neighborNodeIds.add(edge.target);
        neighborEdgeIds.add(edge.id);
      }
      if (edge.target === activeNoteId) {
        neighborNodeIds.add(edge.source);
        neighborEdgeIds.add(edge.id);
      }
    }

    for (const n of filteredGraph.nodes || []) {
      const isCenter = n.id === activeNoteId;
      const isNeighbor = neighborNodeIds.has(n.id);
      const shouldDim = onlyActiveNeighborhood ? !isCenter && !isNeighbor : false;
      graph.setElementState(n.id, "inactive", shouldDim);
      graph.setElementState(n.id, "selected", isCenter);
    }
    for (const e of filteredGraph.edges || []) {
      const shouldDim = onlyActiveNeighborhood ? !neighborEdgeIds.has(e.id) : false;
      graph.setElementState(e.id, "inactive", shouldDim);
    }

    selectedNodeRef.current = activeNoteId;
    graph.focusElement(activeNoteId, true);
    if (shouldZoomOnSelectRef.current) {
      const currentZoom = Number(graph.getZoom?.() || 1);
      const targetZoom = Math.max(1.25, currentZoom);
      graph.zoomTo(targetZoom, { duration: 300 });
      shouldZoomOnSelectRef.current = false;
    }
  }, [activeNoteId, filteredGraph, onlyActiveNeighborhood]);

  useEffect(() => {
    if (!activeNoteId) return;
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(`/api/notes/${activeNoteId}`);
        if (!res.ok) return;
        const data = (await res.json()) as NoteDetailResponse;
        if (cancelled || !data?.note) return;
        setActiveNote(data.note);
        const normalized = (data.relations || []).map((r) => ({
          id: r.id,
          otherId: r.source_note_id === activeNoteId ? r.target_note_id : r.source_note_id,
          type: r.relation_type,
        }));
        setRelatedRelations(normalized);
        const ids = normalized.map((r) => r.otherId).filter((id, idx, arr) => !!id && arr.indexOf(id) === idx).slice(0, 10);
        setRelatedIds(ids);
      } catch {
        // ignore
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [activeNoteId, reloadKey]);

  const nodeById = useMemo(() => {
    const map = new Map<string, GraphNode>();
    for (const n of graphData?.nodes || []) map.set(n.id, n);
    return map;
  }, [graphData]);

  const toggleRelationType = (type: string) => {
    setSelectedRelationTypes((prev) => {
      if (prev.includes(type)) {
        const next = prev.filter((x) => x !== type);
        return next.length ? next : prev;
      }
      return [...prev, type];
    });
  };

  const zoomIn = () => graphRef.current?.zoomBy(1.2);
  const zoomOut = () => graphRef.current?.zoomBy(0.85);
  const fitView = () => graphRef.current?.fitView();
  const resetView = () => {
    const graph = graphRef.current;
    if (!graph) return;
    graph.fitView();
    if (activeNoteId) graph.focusElement(activeNoteId, true);
    try {
      window.localStorage.removeItem(storageKey);
    } catch {
      // ignore
    }
  };

  const createRelation = async () => {
    if (!activeNoteId) return;
    if (!newRelationTargetId) {
      setToast({ type: "error", message: "请先选择目标笔记" });
      return;
    }
    if (newRelationTargetId === activeNoteId) {
      setToast({ type: "error", message: "不能将笔记与自身建立关系" });
      return;
    }
    const duplicate = relatedRelations.some((r) => r.otherId === newRelationTargetId && r.type === newRelationType);
    if (duplicate) {
      setToast({ type: "error", message: "该关系已存在，无需重复添加" });
      return;
    }

    const res = await fetch("/api/note-relations", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        sourceNoteId: activeNoteId,
        targetNoteId: newRelationTargetId,
        relationType: newRelationType,
      }),
    });
    if (!res.ok) {
      let msg = "添加关系失败";
      try {
        const data = await res.json();
        if (data?.error) msg = data.error;
      } catch {
        // ignore
      }
      setToast({ type: "error", message: msg });
      return;
    }
    setNewRelationTargetId("");
    setReloadKey((k) => k + 1);
    setToast({ type: "success", message: "关系已添加" });
  };

  const removeRelation = async (relationId: string) => {
    const ok = window.confirm("确认删除这条关系吗？");
    if (!ok) return;
    const res = await fetch(`/api/note-relations?id=${relationId}`, { method: "DELETE" });
    if (!res.ok) {
      let msg = "删除关系失败";
      try {
        const data = await res.json();
        if (data?.error) msg = data.error;
      } catch {
        // ignore
      }
      setToast({ type: "error", message: msg });
      return;
    }
    setReloadKey((k) => k + 1);
    setToast({ type: "success", message: "关系已删除" });
  };

  const updateRelationType = async (relationId: string) => {
    const nextType = editingRelationTypes[relationId];
    if (!nextType) return;
    const relation = relatedRelations.find((r) => r.id === relationId);
    if (!relation) return;
    if (relation.type === nextType) {
      setToast({ type: "error", message: "关系类型未变化" });
      return;
    }

    const res = await fetch("/api/note-relations", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ relationId, relationType: nextType }),
    });
    if (!res.ok) {
      let msg = "修改关系类型失败";
      try {
        const data = await res.json();
        if (data?.error) msg = data.error;
      } catch {
        // ignore
      }
      setToast({ type: "error", message: msg });
      return;
    }
    setReloadKey((k) => k + 1);
    setToast({ type: "success", message: "关系类型已更新" });
  };

  useEffect(() => {
    if (!toast) return;
    const timer = window.setTimeout(() => setToast(null), 2200);
    return () => window.clearTimeout(timer);
  }, [toast]);

  return (
    <AppLayout>
      <div className="flex flex-col h-full">
        {toast && (
          <div className="absolute right-5 top-5 z-50">
            <div
              className={`px-3 py-2 rounded-md text-xs shadow-md border ${
                toast.type === "success"
                  ? "bg-emerald-50 text-emerald-700 border-emerald-200"
                  : "bg-red-50 text-red-700 border-red-200"
              }`}
            >
              {toast.message}
            </div>
          </div>
        )}
        <div className="px-5 pt-10 pb-6 shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-[3px] h-[18px] bg-[--innex-accent] rounded-sm shrink-0" />
            <span className="text-xl font-[850] text-[--ink] tracking-[-0.2px]">知识图谱</span>
            <span className="text-[11px] text-[#8A8278] font-semibold tracking-[0.12em] uppercase ml-1">KNOWLEDGE GRAPH</span>
          </div>
          <p className="text-xs text-[--text-secondary] mt-1">基于已内化笔记构建的关系图，可拖拽与缩放浏览。</p>
        </div>

        <div className="px-5 pb-4 shrink-0">
          <div className="relative">
            <Input
              placeholder="搜索节点标题或摘要..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-64 h-8 text-xs border-[--border-light] rounded-md pl-7"
            />
            <span className="absolute left-2 top-1/2 -translate-y-1/2 text-xs opacity-40">🔍</span>
          </div>
        </div>

        <div className="flex-1 min-h-0 px-5 pb-8">
          {loading ? (
            <p className="text-sm text-muted-foreground">图谱加载中...</p>
          ) : (
            <div className="grid grid-cols-[1.5fr_0.7fr] gap-4 h-full min-h-0">
              <div className="bg-white rounded-xl border border-[--border-light] min-h-[460px] h-full overflow-hidden relative">
                {error ? (
                  <div className="p-4 text-sm text-red-500">{error}</div>
                ) : filteredGraph.nodes.length === 0 ? (
                  <div className="h-full flex flex-col items-center justify-center text-center px-8">
                    <p className="text-sm text-muted-foreground">知识库为空</p>
                    <p className="text-xs text-muted-foreground mt-1">在收录箱中点击“一键内化”将内容转化为笔记</p>
                  </div>
                ) : (
                  <div ref={graphWrapRef} className="w-full h-full" />
                )}
                {!!filteredGraph.nodes.length && (
                  <div className="absolute right-3 top-3 flex items-center gap-2 bg-white/90 border border-[--border-light] rounded-lg p-1.5 shadow-sm">
                    <button onClick={zoomIn} className="text-xs px-2 py-1 rounded hover:bg-[--innex-accent-dim]">+</button>
                    <button onClick={zoomOut} className="text-xs px-2 py-1 rounded hover:bg-[--innex-accent-dim]">-</button>
                    <button onClick={fitView} className="text-xs px-2 py-1 rounded hover:bg-[--innex-accent-dim]">适配</button>
                    <button onClick={resetView} className="text-xs px-2 py-1 rounded hover:bg-[--innex-accent-dim]">重置</button>
                  </div>
                )}
              </div>

              <div className="bg-white border border-[--border-light] rounded-xl p-4 h-full overflow-auto">
                <div className="mb-3 pb-3 border-b border-[--border-light]">
                  <p className="text-[11px] font-semibold text-[--text-muted] mb-2">关系类型</p>
                  <div className="flex flex-wrap gap-1.5">
                    {relationTypes.length === 0 ? (
                      <span className="text-xs text-muted-foreground">暂无关系</span>
                    ) : (
                      relationTypes.map((t) => {
                        const enabled = selectedRelationTypes.includes(t);
                        return (
                          <button
                            key={t}
                            onClick={() => toggleRelationType(t)}
                            className={`text-[10px] px-2 py-1 rounded border transition-colors ${
                              enabled
                                ? "border-[--innex-accent] text-[--innex-accent] bg-[--innex-accent-dim]"
                                : "border-[--border-light] text-[--text-secondary] hover:border-[--innex-accent]"
                            }`}
                          >
                            {t}
                          </button>
                        );
                      })
                    )}
                  </div>
                  <div className="mt-2.5 flex flex-wrap gap-2">
                    {relationTypes.map((t) => (
                      <div key={`legend-${t}`} className="flex items-center gap-1.5 text-[10px] text-[--text-secondary]">
                        <span className="inline-block w-2.5 h-2.5 rounded-full" style={{ backgroundColor: relationColor(t) }} />
                        <span>{t}</span>
                      </div>
                    ))}
                  </div>
                  <label className="mt-3 flex items-center gap-2 text-[11px] text-[--text-secondary] cursor-pointer select-none">
                    <input
                      type="checkbox"
                      checked={onlyActiveNeighborhood}
                      onChange={(e) => setOnlyActiveNeighborhood(e.target.checked)}
                      className="w-3.5 h-3.5 rounded border-[--border-light]"
                    />
                    仅显示与当前节点相关关系
                  </label>
                  <label className="mt-2 flex items-center gap-2 text-[11px] text-[--text-secondary] cursor-pointer select-none">
                    <input
                      type="checkbox"
                      checked={onlyHighConfidence}
                      onChange={(e) => setOnlyHighConfidence(e.target.checked)}
                      className="w-3.5 h-3.5 rounded border-[--border-light]"
                    />
                    仅显示高置信关系（{"≥"} 0.75）
                  </label>
                </div>

                {!activeNote ? (
                  <p className="text-xs text-muted-foreground">点击图谱节点查看详情</p>
                ) : (
                  <div className="space-y-3">
                    <div>
                      <h3 className="font-semibold text-[13px] text-[--ink] leading-snug">{activeNote.title}</h3>
                      {activeNote.summary && <p className="text-xs text-[--text-secondary] mt-1.5">{activeNote.summary}</p>}
                      <p className="text-[10px] text-muted-foreground mt-2">
                        {activeNote.source || "未知来源"} · {formatDate(activeNote.created_at)}
                      </p>
                    </div>

                    <div className="flex gap-1.5 flex-wrap">
                      {activeNote.concepts?.slice(0, 6).map((c) => (
                        <span key={c} className="text-[10px] px-1.5 py-0.5 rounded bg-[--innex-accent-dim] text-[--innex-accent]">
                          {c}
                        </span>
                      ))}
                    </div>

                    <div>
                      <p className="text-[11px] font-semibold text-[--text-muted] mb-1">关联笔记</p>
                      {relatedIds.length === 0 ? (
                        <p className="text-xs text-muted-foreground">暂无关联笔记</p>
                      ) : (
                        <div className="flex flex-wrap gap-1.5">
                          {relatedIds.map((id) => {
                            const n = nodeById.get(id);
                            if (!n) return null;
                            return (
                              <button
                                key={id}
                                onClick={() => setActiveNoteId(id)}
                                className="text-[11px] px-2 py-1 rounded-md border border-[--border-light] bg-[--paper-light] hover:border-[--innex-accent] hover:text-[--innex-accent] transition-colors"
                                title={n.label}
                              >
                                {n.label.length > 16 ? `${n.label.slice(0, 16)}...` : n.label}
                              </button>
                            );
                          })}
                        </div>
                      )}
                    </div>

                    <div className="pt-2 border-t border-[--border-light]">
                      <p className="text-[11px] font-semibold text-[--text-muted] mb-2">手动修边</p>
                      <div className="space-y-2">
                        <select
                          value={newRelationTargetId}
                          onChange={(e) => setNewRelationTargetId(e.target.value)}
                          className="w-full h-8 text-xs border border-[--border-light] rounded-md px-2 bg-white"
                        >
                          <option value="">选择目标笔记</option>
                          {(graphData?.nodes || [])
                            .filter((n) => n.id !== activeNoteId)
                            .map((n) => (
                              <option key={n.id} value={n.id}>
                                {n.label}
                              </option>
                            ))}
                        </select>
                        <select
                          value={newRelationType}
                          onChange={(e) => setNewRelationType(e.target.value)}
                          className="w-full h-8 text-xs border border-[--border-light] rounded-md px-2 bg-white"
                        >
                          <option value="related">related</option>
                          <option value="extends">extends</option>
                          <option value="contradicts">contradicts</option>
                          <option value="derives_from">derives_from</option>
                        </select>
                        <button
                          onClick={createRelation}
                          className="w-full h-8 text-xs rounded-md bg-[--innex-accent] text-white hover:bg-[--innex-accent-hover]"
                        >
                          添加关系
                        </button>
                      </div>

                      <div className="mt-3 space-y-1.5">
                        {relatedRelations.length === 0 ? (
                          <p className="text-xs text-muted-foreground">暂无可删除关系</p>
                        ) : (
                          relatedRelations.map((rel) => {
                            const target = nodeById.get(rel.otherId);
                            const editingType = editingRelationTypes[rel.id] || rel.type;
                            return (
                              <div key={rel.id} className="flex items-center gap-2 border border-[--border-light] rounded-md px-2 py-1.5">
                                <select
                                  value={editingType}
                                  onChange={(e) =>
                                    setEditingRelationTypes((prev) => ({
                                      ...prev,
                                      [rel.id]: e.target.value,
                                    }))
                                  }
                                  className="h-7 text-[10px] border border-[--border-light] rounded px-1 bg-white"
                                >
                                  <option value="related">related</option>
                                  <option value="extends">extends</option>
                                  <option value="contradicts">contradicts</option>
                                  <option value="derives_from">derives_from</option>
                                </select>
                                <span className="text-xs text-[--text-secondary] flex-1 truncate">{target?.label || rel.otherId}</span>
                                <button
                                  onClick={() => updateRelationType(rel.id)}
                                  className="text-[10px] px-2 py-1 rounded border border-blue-200 text-blue-600 hover:bg-blue-50"
                                >
                                  保存
                                </button>
                                <button
                                  onClick={() => removeRelation(rel.id)}
                                  className="text-[10px] px-2 py-1 rounded border border-red-200 text-red-600 hover:bg-red-50"
                                >
                                  删除
                                </button>
                              </div>
                            );
                          })
                        )}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </AppLayout>
  );
}
