import { createClient } from "@/lib/supabase/server";
import { NextRequest, NextResponse } from "next/server";

const DEFAULT_LIMIT = 300;
const MAX_LIMIT = 1000;
const ALLOWED_RELATION_TYPES = new Set(["related", "supports", "example_of", "weak_related", "fallback"]);

type GraphNode = {
  id: string;
  label: string;
  summary: string | null;
  tags: string[];
  concepts: string[];
  source: string | null;
  sourceUrl: string | null;
  captureItemId: string | null;
  createdAt: string;
  updatedAt: string;
  degree: number;
};

type GraphEdge = {
  id: string;
  source: string;
  target: string;
  type: string;
  confidence: number | null;
  evidence: Record<string, unknown> | null;
  isAutoGenerated: boolean | null;
  createdAt: string;
};

export async function GET(request: NextRequest) {
  const startedAt = Date.now();
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { searchParams } = request.nextUrl;
  const search = searchParams.get("search")?.trim() || "";
  const tag = searchParams.get("tag")?.trim() || "";
  const concept = searchParams.get("concept")?.trim() || "";
  const mode = "note";
  const focusNoteId = searchParams.get("focusNoteId")?.trim() || null;
  const centerNoteId = searchParams.get("centerNoteId")?.trim() || null;
  const rawHops = Number(searchParams.get("hops") || "0");
  const hops = Number.isFinite(rawHops) ? Math.max(0, Math.min(4, Math.floor(rawHops))) : 0;

  const rawLimit = Number(searchParams.get("limit"));
  const limit = Number.isFinite(rawLimit)
    ? Math.min(Math.max(Math.floor(rawLimit), 1), MAX_LIMIT)
    : DEFAULT_LIMIT;

  let notesQuery = supabase
    .from("notes")
    .select("id, title, summary, tags, concepts, source, source_url, capture_item_id, created_at, updated_at", { count: "exact" })
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .limit(limit);

  if (search) {
    notesQuery = notesQuery.or(`title.ilike.%${search}%,summary.ilike.%${search}%`);
  }
  if (tag) {
    notesQuery = notesQuery.contains("tags", [tag]);
  }
  if (concept) {
    notesQuery = notesQuery.contains("concepts", [concept]);
  }

  const { data: notes, error: notesError, count } = await notesQuery;
  if (notesError) {
    return NextResponse.json({ error: notesError.message }, { status: 500 });
  }

  let noteList = notes || [];
  const captureIds = noteList.map((n) => n.capture_item_id).filter(Boolean);
  if (captureIds.length > 0) {
    const { data: captureRows } = await supabase
      .from("capture_items")
      .select("id, status")
      .eq("user_id", user.id)
      .in("id", captureIds as string[]);
    const statusMap = new Map<string, string>((captureRows || []).map((x) => [x.id, x.status]));
    // Strict mode: only show crystallized notes in graph.
    noteList = noteList.filter((n) => !!n.capture_item_id && statusMap.get(n.capture_item_id) === "crystallized");
  } else {
    noteList = [];
  }

  // Safety de-duplication by note id.
  noteList = Array.from(new Map(noteList.map((n) => [n.id, n])).values());
  if (noteList.length === 0) {
    return NextResponse.json({
      nodes: [],
      edges: [],
      meta: {
        nodeCount: 0,
        edgeCount: 0,
        truncated: false,
        limit,
        focusNoteId,
      },
    });
  }

  const noteIds = noteList.map((n) => n.id);

  type RelationRow = {
    id: string;
    source_note_id: string;
    target_note_id: string;
    relation_type: string;
    confidence?: number | null;
    evidence?: Record<string, unknown> | null;
    is_auto_generated?: boolean | null;
    created_at: string;
  };
  let relations: RelationRow[] = [];

  const relNew = await supabase
    .from("note_relations")
    .select("id, source_note_id, target_note_id, relation_type, confidence, evidence, is_auto_generated, created_at")
    .eq("user_id", user.id)
    .in("source_note_id", noteIds)
    .in("target_note_id", noteIds);

  if (relNew.error && String(relNew.error.message || "").includes("column")) {
    const relOld = await supabase
      .from("note_relations")
      .select("id, source_note_id, target_note_id, relation_type, created_at")
      .eq("user_id", user.id)
      .in("source_note_id", noteIds)
      .in("target_note_id", noteIds);
    if (relOld.error) return NextResponse.json({ error: relOld.error.message }, { status: 500 });
    relations = (relOld.data || []) as RelationRow[];
  } else if (relNew.error) {
    return NextResponse.json({ error: relNew.error.message }, { status: 500 });
  } else {
    relations = (relNew.data || []) as RelationRow[];
  }

  const degreeMap = new Map<string, number>();
  for (const id of noteIds) degreeMap.set(id, 0);

  const seenEdges = new Set<string>();
  const edges: GraphEdge[] = relations
    .filter((r) => r.source_note_id !== r.target_note_id)
    .filter((r) => ALLOWED_RELATION_TYPES.has(r.relation_type))
    .filter((r) => {
      const a = r.source_note_id < r.target_note_id ? r.source_note_id : r.target_note_id;
      const b = r.source_note_id < r.target_note_id ? r.target_note_id : r.source_note_id;
      const key = `${a}|${b}|${r.relation_type}`;
      if (seenEdges.has(key)) return false;
      seenEdges.add(key);
      return true;
    })
    .map((r) => {
    degreeMap.set(r.source_note_id, (degreeMap.get(r.source_note_id) || 0) + 1);
    degreeMap.set(r.target_note_id, (degreeMap.get(r.target_note_id) || 0) + 1);
    return {
      id: r.id,
      source: r.source_note_id,
      target: r.target_note_id,
      type: r.relation_type,
      confidence: typeof r.confidence === "number" ? r.confidence : null,
      evidence: r.evidence || null,
      isAutoGenerated: typeof r.is_auto_generated === "boolean" ? r.is_auto_generated : null,
      createdAt: r.created_at,
    };
  });

  const nodes: GraphNode[] = noteList.map((n) => ({
    id: n.id,
    label: n.title,
    summary: n.summary,
    tags: n.tags || [],
    concepts: n.concepts || [],
    source: n.source,
    sourceUrl: n.source_url,
    captureItemId: n.capture_item_id,
    createdAt: n.created_at,
    updatedAt: n.updated_at,
    degree: degreeMap.get(n.id) || 0,
  }));

  let finalNodes = nodes;
  let finalEdges = edges;
  if (centerNoteId && hops > 0) {
    const adjacency = new Map<string, Set<string>>();
    for (const n of nodes) adjacency.set(n.id, new Set<string>());
    for (const e of edges) {
      adjacency.get(e.source)?.add(e.target);
      adjacency.get(e.target)?.add(e.source);
    }

    const visited = new Set<string>([centerNoteId]);
    let frontier = new Set<string>([centerNoteId]);
    for (let i = 0; i < hops; i++) {
      const next = new Set<string>();
      for (const id of frontier) {
        for (const nei of adjacency.get(id) || []) {
          if (!visited.has(nei)) {
            visited.add(nei);
            next.add(nei);
          }
        }
      }
      frontier = next;
      if (frontier.size === 0) break;
    }
    finalNodes = nodes.filter((n) => visited.has(n.id));
    const allowed = new Set(finalNodes.map((n) => n.id));
    finalEdges = edges.filter((e) => allowed.has(e.source) && allowed.has(e.target));
  }

  const relationTypeCounts = finalEdges.reduce<Record<string, number>>((acc, e) => {
    acc[e.type] = (acc[e.type] || 0) + 1;
    return acc;
  }, {});

  const confidenceStats = {
    high: finalEdges.filter((e) => typeof e.confidence === "number" && e.confidence >= 0.75).length,
    mid: finalEdges.filter((e) => typeof e.confidence === "number" && e.confidence >= 0.6 && e.confidence < 0.75).length,
    low: finalEdges.filter((e) => typeof e.confidence === "number" && e.confidence < 0.6).length,
    unknown: finalEdges.filter((e) => typeof e.confidence !== "number").length,
  };

  const durationMs = Date.now() - startedAt;
  console.info("[graph.api]", {
    user_id: user.id,
    node_count: finalNodes.length,
    edge_count: finalEdges.length,
    duration_ms: durationMs,
    truncated: (count || 0) > limit,
    center_note_id: centerNoteId,
    hops,
  });

  return NextResponse.json({
    nodes: finalNodes,
    edges: finalEdges,
    meta: {
      nodeCount: finalNodes.length,
      edgeCount: finalEdges.length,
      truncated: (count || 0) > limit,
      limit,
      focusNoteId,
      centerNoteId,
      hops,
      mode,
      durationMs,
      relationTypeCounts,
      confidenceStats,
    },
  });
}
