import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

const ALLOWED_TYPES = new Set(["related", "extends", "contradicts", "derives_from"]);

export async function POST(request: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { sourceNoteId, targetNoteId, relationType, confidence, evidence, isAutoGenerated } = await request.json();
  if (!sourceNoteId || !targetNoteId) {
    return NextResponse.json({ error: "sourceNoteId and targetNoteId are required" }, { status: 400 });
  }
  if (sourceNoteId === targetNoteId) {
    return NextResponse.json({ error: "Cannot relate note to itself" }, { status: 400 });
  }
  const type = ALLOWED_TYPES.has(relationType) ? relationType : "related";

  const { data: notes, error: notesError } = await supabase
    .from("notes")
    .select("id")
    .eq("user_id", user.id)
    .in("id", [sourceNoteId, targetNoteId]);

  if (notesError || !notes || notes.length !== 2) {
    return NextResponse.json({ error: "Source/target note not found" }, { status: 404 });
  }

  const { data: existing } = await supabase
    .from("note_relations")
    .select("id")
    .eq("user_id", user.id)
    .eq("source_note_id", sourceNoteId)
    .eq("target_note_id", targetNoteId)
    .eq("relation_type", type)
    .maybeSingle();

  if (existing) {
    return NextResponse.json({ error: "Relation already exists" }, { status: 409 });
  }

  const insertPayload = {
    user_id: user.id,
    source_note_id: sourceNoteId,
    target_note_id: targetNoteId,
    relation_type: type,
    confidence: typeof confidence === "number" ? confidence : null,
    evidence: evidence && typeof evidence === "object" ? evidence : {},
    is_auto_generated: typeof isAutoGenerated === "boolean" ? isAutoGenerated : false,
  };

  let data: unknown = null;
  let error: { message?: string } | null = null;
  const inserted = await supabase.from("note_relations").insert(insertPayload).select().single();
  if (inserted.error && String(inserted.error.message || "").includes("column")) {
    const fallback = await supabase
      .from("note_relations")
      .insert({
        user_id: user.id,
        source_note_id: sourceNoteId,
        target_note_id: targetNoteId,
        relation_type: type,
      })
      .select()
      .single();
    data = fallback.data;
    error = fallback.error;
  } else {
    data = inserted.data;
    error = inserted.error;
  }

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ relation: data }, { status: 201 });
}

export async function DELETE(request: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { searchParams } = new URL(request.url);
  const relationId = searchParams.get("id");
  if (!relationId) return NextResponse.json({ error: "id is required" }, { status: 400 });

  const { error } = await supabase
    .from("note_relations")
    .delete()
    .eq("id", relationId)
    .eq("user_id", user.id);

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ success: true });
}

export async function PATCH(request: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { relationId, relationType, confidence, evidence, isAutoGenerated } = await request.json();
  if (!relationId) return NextResponse.json({ error: "relationId is required" }, { status: 400 });
  if (!relationType || !ALLOWED_TYPES.has(relationType)) {
    return NextResponse.json({ error: "Invalid relationType" }, { status: 400 });
  }

  const { data: existing, error: existingError } = await supabase
    .from("note_relations")
    .select("id, source_note_id, target_note_id, relation_type")
    .eq("id", relationId)
    .eq("user_id", user.id)
    .single();

  if (existingError || !existing) return NextResponse.json({ error: "Relation not found" }, { status: 404 });
  if (existing.relation_type === relationType) {
    return NextResponse.json({ relation: existing }, { status: 200 });
  }

  const { data: duplicate } = await supabase
    .from("note_relations")
    .select("id")
    .eq("user_id", user.id)
    .eq("source_note_id", existing.source_note_id)
    .eq("target_note_id", existing.target_note_id)
    .eq("relation_type", relationType)
    .maybeSingle();

  if (duplicate) return NextResponse.json({ error: "Relation already exists with this type" }, { status: 409 });

  const updatePayload: Record<string, unknown> = { relation_type: relationType };
  if (typeof confidence === "number") updatePayload.confidence = confidence;
  if (evidence && typeof evidence === "object") updatePayload.evidence = evidence;
  if (typeof isAutoGenerated === "boolean") updatePayload.is_auto_generated = isAutoGenerated;

  let data: unknown = null;
  let error: { message?: string } | null = null;
  const updated = await supabase
    .from("note_relations")
    .update(updatePayload)
    .eq("id", relationId)
    .eq("user_id", user.id)
    .select()
    .single();

  if (updated.error && String(updated.error.message || "").includes("column")) {
    const fallback = await supabase
      .from("note_relations")
      .update({ relation_type: relationType })
      .eq("id", relationId)
      .eq("user_id", user.id)
      .select()
      .single();
    data = fallback.data;
    error = fallback.error;
  } else {
    data = updated.data;
    error = updated.error;
  }

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ relation: data }, { status: 200 });
}
